# Importing the required libraries

### Importing and Pandas configurations
Here we are importing the os and glob to read multiple datafiles to python code/env
Also setting up the pandas df display settings

In [1]:
import os
import glob
import pandas as pd
import numpy as np
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

### Gathering the data
Gathering all the csv files from the given folder path and storing them in all files

In [ ]:
#Grab all CSV paths from your target folder
folder_path = r"X:\Powerbi\Projects\Brazillian_ecommerce_analysis\Data"
all_files = glob.glob(os.path.join(folder_path, "*.csv"))

# Extracting the Structural data and Health profiles

In [17]:
# 2. Extract structural data health profiles
file_profiles =[]
dfs =[]
column_def=[]
describe_prf=[]
null_count=[]
samples_f=[]
for file in all_files:
    try:
        # Load sample or full file depending on size
        df_temp = pd.read_csv(file) # Quick check on first 1000 rows with nrows=1000
        
        profile = {
            "File_Name": os.path.basename(file),
            "Row_Count_Sample": len(df_temp),
            "Column_Count": len(df_temp.columns),
            #"Columns": list(df_temp.columns),
            "Missing_Values_Total": df_temp.isnull().sum().sum()
        }
        column_prf={
            "File_Name": os.path.basename(file),
            "Column names": list(df_temp.columns)
        }
        nullcntf={
            "File_Name": os.path.basename(file),
            "Null columns": df_temp.isnull().sum()
        }
        des_prf={
            "File_Name": os.path.basename(file),
            "Describe": df_temp.describe(include="all")
        }
        samples={
            "File_Name": os.path.basename(file),
            "Samples": df_temp.sample(10)
        }

        
        file_profiles.append(profile)
        column_def.append(column_prf)
        null_count.append(nullcntf)
        describe_prf.append(des_prf)
        samples_f.append(samples)

        # Keep track for final master merge
        #dfs.append(pd.read_csv(file))
    except Exception as e:
        print(f"⚠️ Structural error found in file {os.path.basename(file)}: {e}")

In [18]:
# Validate if all files match column layouts
profile_df = pd.DataFrame(file_profiles)
profile_df

# 3. If clean, consolidate into a master staging dataframe
#if len(dfs) > 0:
#    master_df = pd.concat(dfs, ignore_index=True)
#    # Save a staging dataset
#    master_df.to_csv(os.path.join(folder_path, "master_staging.csv"), index=False)

,File_Name,Row_Count_Sample,Column_Count,Missing_Values_Total
0,olist_customers_dataset.csv,99441,5,0
1,olist_geolocation_dataset.csv,1000163,5,0
2,olist_orders_dataset.csv,99441,8,4908
3,olist_order_items_dataset.csv,112650,7,0
4,olist_order_payments_dataset.csv,103886,5,0
5,olist_order_reviews_dataset.csv,99224,7,145903
6,olist_products_dataset.csv,32951,9,2448
7,olist_sellers_dataset.csv,3095,4,0
8,product_category_name_translation.csv,71,2,0

In [19]:
column_df=pd.DataFrame(column_def)
column_df

,File_Name,Column names
0,olist_customers_dataset.csv,"[customer_id, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state]"
1,olist_geolocation_dataset.csv,"[geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state]"
2,olist_orders_dataset.csv,"[order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]"
3,olist_order_items_dataset.csv,"[order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]"
4,olist_order_payments_dataset.csv,"[order_id, payment_sequential, payment_type, payment_installments, payment_value]"
5,olist_order_reviews_dataset.csv,"[review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]"
6,olist_products_dataset.csv,"[product_id, product_category_name, product_name_lenght, product_description_lenght, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm]"
7,olist_sellers_dataset.csv,"[seller_id, seller_zip_code_prefix, seller_city, seller_state]"
8,product_category_name_translation.csv,"[product_category_name, product_category_name_english]"

In [20]:
for item in null_count:
    s = item["Null columns"]
    s = s[s > 0]

    if s.empty:
        pass
        #print(item["File_Name"])
        #print("No null values\n")
    else:
        print(item["File_Name"])
        display(s.to_frame("null_count"))
        #print(s)

olist_orders_dataset.csv

                               null_count
order_approved_at                     160
order_delivered_carrier_date         1783
order_delivered_customer_date        2965

olist_order_reviews_dataset.csv

                        null_count
review_comment_title         87656
review_comment_message       58247

olist_products_dataset.csv

                            null_count
product_category_name              610
product_name_lenght                610
product_description_lenght         610
product_photos_qty                 610
product_weight_g                     2
product_length_cm                    2
product_height_cm                    2
product_width_cm                     2

In [22]:
for item in describe_prf:
  print(item["File_Name"])
  display(item["Describe"])

olist_customers_dataset.csv

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441.000000,99441,99441
unique,99441,96096,NaN,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,NaN,sao paulo,SP
freq,1,17,NaN,15540,41746
mean,NaN,NaN,35137.474583,NaN,NaN
std,NaN,NaN,29797.938996,NaN,NaN
min,NaN,NaN,1003.000000,NaN,NaN
25%,NaN,NaN,11347.000000,NaN,NaN
50%,NaN,NaN,24416.000000,NaN,NaN
75%,NaN,NaN,58900.000000,NaN,NaN
max,NaN,NaN,99990.000000,NaN,NaN

olist_geolocation_dataset.csv

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
count,1.000163e+06,1.000163e+06,1.000163e+06,1000163,1000163
unique,NaN,NaN,NaN,8011,27
top,NaN,NaN,NaN,sao paulo,SP
freq,NaN,NaN,NaN,135800,404268
mean,3.657417e+04,-2.117615e+01,-4.639054e+01,NaN,NaN
std,3.054934e+04,5.715866e+00,4.269748e+00,NaN,NaN
min,1.001000e+03,-3.660537e+01,-1.014668e+02,NaN,NaN
25%,1.107500e+04,-2.360355e+01,-4.857317e+01,NaN,NaN
50%,2.653000e+04,-2.291938e+01,-4.663788e+01,NaN,NaN
75%,6.350400e+04,-1.997962e+01,-4.376771e+01,NaN,NaN
max,9.999000e+04,4.506593e+01,1.211054e+02,NaN,NaN

olist_orders_dataset.csv

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

olist_order_items_dataset.csv

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
count,112650,112650.000000,112650,112650,112650,112650.000000,112650.000000
unique,98666,NaN,32951,3095,93318,NaN,NaN
top,8272b63d03f5f79c56e9e4120aec44ef,NaN,aca2eb7d00ea1a7b8ebd4e68314663af,6560211a19b47992c3666cc44a7e94c0,2018-03-01 02:50:48,NaN,NaN
freq,21,NaN,527,2033,21,NaN,NaN
mean,NaN,1.197834,NaN,NaN,NaN,120.653739,19.990320
std,NaN,0.705124,NaN,NaN,NaN,183.633928,15.806405
min,NaN,1.000000,NaN,NaN,NaN,0.850000,0.000000
25%,NaN,1.000000,NaN,NaN,NaN,39.900000,13.080000
50%,NaN,1.000000,NaN,NaN,NaN,74.990000,16.260000
75%,NaN,1.000000,NaN,NaN,NaN,134.900000,21.150000
max,NaN,21.000000,NaN,NaN,NaN,6735.000000,409.680000

olist_order_payments_dataset.csv

,order_id,payment_sequential,payment_type,payment_installments,payment_value
count,103886,103886.000000,103886,103886.000000,103886.000000
unique,99440,NaN,5,NaN,NaN
top,fa65dad1b0e818e3ccc5cb0e39231352,NaN,credit_card,NaN,NaN
freq,29,NaN,76795,NaN,NaN
mean,NaN,1.092679,NaN,2.853349,154.100380
std,NaN,0.706584,NaN,2.687051,217.494064
min,NaN,1.000000,NaN,0.000000,0.000000
25%,NaN,1.000000,NaN,1.000000,56.790000
50%,NaN,1.000000,NaN,1.000000,100.000000
75%,NaN,1.000000,NaN,4.000000,171.837500
max,NaN,29.000000,NaN,24.000000,13664.080000

olist_order_reviews_dataset.csv

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
count,99224,99224,99224.000000,11568,40977,99224,99224
unique,98410,98673,NaN,4527,36159,636,98248
top,c444278834184f72b1484dfe47de7f97,c88b1d1b157a9999ce368f218a407141,NaN,Recomendo,Muito bom,2017-12-19 00:00:00,2017-06-15 23:21:05
freq,3,3,NaN,423,230,463,4
mean,NaN,NaN,4.086421,NaN,NaN,NaN,NaN
std,NaN,NaN,1.347579,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,5.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,5.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,5.000000,NaN,NaN,NaN,NaN

olist_products_dataset.csv

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32951,32341,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
unique,32951,73,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,1e9e8ef04dbcff4541ed26657ea517e5,cama_mesa_banho,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,3029,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,NaN,NaN,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,NaN,NaN,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,NaN,NaN,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,NaN,NaN,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,NaN,NaN,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,NaN,NaN,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

olist_sellers_dataset.csv

,seller_id,seller_zip_code_prefix,seller_city,seller_state
count,3095,3095.000000,3095,3095
unique,3095,NaN,611,23
top,3442f8959a84dea7ee197c632cb2df15,NaN,sao paulo,SP
freq,1,NaN,694,1849
mean,NaN,32291.059451,NaN,NaN
std,NaN,32713.453830,NaN,NaN
min,NaN,1001.000000,NaN,NaN
25%,NaN,7093.500000,NaN,NaN
50%,NaN,14940.000000,NaN,NaN
75%,NaN,64552.500000,NaN,NaN
max,NaN,99730.000000,NaN,NaN

product_category_name_translation.csv

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [26]:
for item in samples_f:
  display(item["Samples"])

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
82365,cc427818670e1a876ce1a0c989d92f68,a984dc73180e58d6b3520c7e32dd33c9,3321,sao paulo,SP
33248,e35a269a4bf5db26948c1d6105611225,4edc601b95352e37be4af8a3fc1c133e,94853,alvorada,RS
57590,44b6daee2ecd7c8dc15781c3152f89fe,4563f015c75458c8d23647e56b6cfe7c,26278,nova iguacu,RJ
9510,63da2e8fde0e3a1b064e9641ffdae56a,3bb93645d4027fa9d5c6baf691ba2a37,86020,londrina,PR
35669,04802886a43fe74bd00496abf197b3a6,971c2c9f771f31f9e88687edf04f37c1,8773,mogi das cruzes,SP
62159,af35c1eb9f66ae71152e988e0f1bdae8,bb1d9cb6005629522055ccce642cfc73,6124,osasco,SP
46463,e25a23b6ec8f03463e9b45176b59fc89,a7e81ef44420c32ed404201355a14e14,4888,sao paulo,SP
83178,5def4c024799f5734e4651ff6c889f4d,1cc14c8b94f04f741b41b9c22ebd634f,32315,contagem,MG
49371,4d5a3f2707cfa16d395c679bea6c204c,e399db816ed3a4918576d99641c3668b,96200,rio grande,RS
81729,f3b3891ff0afe3e2d70489634fb1bfbd,917ecc45f6867afc87a8351389bd75f5,23068,rio de janeiro,RJ

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
752523,64005,-5.039408,-42.831172,teresina,PI
548409,30350,-19.946666,-43.944592,belo horizonte,MG
782468,70711,-15.788460,-47.882610,brasilia,DF
839116,79560,-18.796484,-52.626924,chapadão do sul,MS
583049,34800,-19.883995,-43.672214,caeté,MG
579186,33400,-19.633432,-43.899342,lagoa santa,MG
877083,85805,-24.960692,-53.488059,cascavel,PR
453132,22631,-23.002163,-43.327734,rio de janeiro,RJ
785672,71710,-15.865364,-47.960893,brasília,DF
459808,23082,-22.889563,-43.571136,rio de janeiro,RJ

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
50816,404427f6508b6a779e273ad67a7ba350,a585bc2d80028318b3edc2347f3c4277,delivered,2017-10-11 20:17:39,2017-10-11 20:28:22,2017-10-31 09:17:05,2017-10-31 16:42:49,2017-10-30 00:00:00
70764,00d15ff0236872686e4899ed1ce680ad,8ebb06c13ec14673af1630a22715f4bd,delivered,2018-08-07 16:33:59,2018-08-09 03:55:11,2018-08-14 15:24:00,2018-08-21 19:04:31,2018-08-30 00:00:00
80427,1303938f4e61db6da994b6d00e34e7b0,d7d6d2aa2c72b6e7815a44ca8278f7b9,delivered,2017-11-20 12:47:57,2017-11-20 13:07:09,2017-11-21 02:36:58,2017-12-06 00:57:43,2017-12-26 00:00:00
86685,0f8415c6898be42b337b26a77fcecbee,989f677f902616c785e3681d2fe63b75,delivered,2018-08-01 11:11:04,2018-08-01 12:30:36,2018-08-03 13:50:00,2018-08-10 18:18:21,2018-08-20 00:00:00
28813,6dc82b96e967ee5e211d1690573f8de5,4c77c973538d06c6c1fd404abaf885f8,delivered,2018-02-21 10:22:09,2018-02-22 02:10:31,2018-02-22 22:47:01,2018-02-28 14:19:20,2018-03-15 00:00:00
22588,fb7a9e3e0ff0d94790b472206462f2de,cec58a230b3feb0e56a802540eb8b28d,delivered,2017-06-15 07:42:43,2017-06-15 07:50:14,2017-06-19 14:56:01,2017-06-19 18:46:44,2017-06-29 00:00:00
16040,aee1ebae09f6d91ca6a459bf47b14072,07cc6026f1fba9869ce6efc681fd190d,delivered,2018-04-10 07:39:30,2018-04-11 09:11:51,2018-04-12 02:42:36,2018-04-17 16:58:28,2018-05-04 00:00:00
48556,566fe59dc8f089f27c0e739a3891581a,38d54a9478904bfa6d7fca2b36be9fdf,delivered,2017-08-03 11:03:47,2017-08-03 13:55:07,2017-08-07 19:15:38,2017-08-08 17:18:00,2017-08-16 00:00:00
92108,0b16257b1b7ee0922ea03954f2cae85a,b0344db4bb1741ab32ee52ef092b2572,canceled,2018-08-07 18:31:25,2018-08-07 18:44:50,NaN,NaN,2018-08-10 00:00:00
65425,3e94e8193697342790ce0f1f8876fdc7,7983c699f34e9ba67e1556feca9cf98d,delivered,2018-01-13 21:27:52,2018-01-16 03:36:40,2018-01-16 22:52:20,2018-01-24 19:49:07,2018-02-05 00:00:00

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
44855,66030147ffa4f133089e5b7578977ac7,1,4ac533f3cdb87b7764bf5fd518a85bda,54965bbe3e4f07ae045b90b0b8541f52,2017-11-09 12:10:29,80.00,28.96
10061,171a1f1ee5fb6ee190e46e3a9dbf85c7,1,a02d0123079f4ae96001ba2010d1a2df,1025f0e2d44d7041d6cf58b6550e0bfa,2018-07-30 10:23:55,228.00,34.68
95367,d849519c380fc7427ba88fc312ade389,1,16d5f9047931834bc4634f3190e575fe,76d5af76d0271110f9af36c92573f765,2018-02-15 15:48:25,345.50,38.00
97021,dc1db1e1520b30e1d279a28b53a2f169,3,e9728f36e661801abf1730782e00a0f3,cac4c8e7b1ca6252d8f20b2fc1a2e4af,2018-02-27 19:15:48,10.99,11.85
11705,1a94ab8fa44ab78eedc4ec633f54cc02,1,8ed094bfe076c568f6bb10feada3f75d,7c67e1448b00f6e969d365cea6b010ab,2018-02-02 05:32:47,192.99,34.62
108979,f7a6a012fe2322e9fae5ad8b10385f15,1,3f40e0e434d939f380a29f5e863cfb9f,729f06993dac8e860d4f02d7088ca48a,2017-04-04 14:02:41,129.90,13.49
50340,7267e79548a97a01f870d9554ecbf645,1,588ea3decc0d8e1d19ce6160c5b0da1b,955fee9216a65b617aa5c0531780ce60,2017-12-06 21:57:02,169.00,17.43
31850,48355743de20d2abaed10440296594e5,1,013b5dd7d319685753e2c12292975615,099095b050cfe8eb1ddff5317587e96e,2018-04-19 20:51:48,265.99,96.82
38410,573b067a37070f89ee054b516f889171,1,c20e9c8a7361bfa0d6530ab73075921b,f46490624488d3ff7ce78613913a7711,2018-08-20 14:15:21,79.00,23.35
77586,b09c529b0885805d42c10a62aa2f31be,1,c9c6fde711572c1ad99ca12728c6af00,562fc2f2c2863ab7e79a9e4388a58a14,2018-05-18 08:13:57,29.99,14.28

,order_id,payment_sequential,payment_type,payment_installments,payment_value
99594,1ec2e1de3e116559a59ec5166697d334,1,credit_card,3,177.77
95706,216b6395628241d62abe56159c7a3841,1,credit_card,5,54.61
75670,e8df3922b27283e487dfe7c7c0eb149b,1,boleto,1,70.14
9951,e66c28c44f4a12382611f0de3e522478,1,credit_card,1,155.98
56990,cdc8b4ad3c6deb7fc303fb91abe7bc0f,1,credit_card,2,292.28
52451,7db96860cb4e02a87c7f0a97c48496d6,1,credit_card,5,113.59
84979,ca37d18bde9cdb0ba2b129d3ecabfd04,1,boleto,1,224.94
93320,f92cfbd80ead6ae168b77674a374b196,1,credit_card,5,111.93
96470,e2fb90759edabe8462da889ac54fb0b1,1,credit_card,5,54.89
38692,153f3406d034142db04fcb576d6987cc,1,credit_card,1,97.76

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
7977,1767e69a2c7bf6c9334ecf37b76b434b,570b8c11496979f54bf5bb027e86fcd2,5,NaN,O produto é nota 10.,2017-10-28 00:00:00,2017-10-28 23:37:47
60274,482fb5cf3364f2f524ff86a0c3412588,68c47b8460f7f1e30cc524010aae7464,4,NaN,NaN,2018-03-28 00:00:00,2018-04-02 13:00:10
44198,04a0fc9bfa5701a81f1232c4e882167f,2b8f925d21cb444a3118d0640bb09cc1,4,NaN,NaN,2018-04-03 00:00:00,2018-04-05 17:29:31
44177,79b057fe934639ac76007de146f37988,9cfa13a566f8072bb6af2c225db04e5f,4,NaN,NaN,2018-07-06 00:00:00,2018-07-08 23:09:27
54276,aefef913b08490efa7de7a533884a3cd,9a817712555d1bbd18414531f1211275,5,NaN,Tudo correu dentro do previsto. Obrigada!,2018-02-23 00:00:00,2018-03-08 11:13:38
19910,5e45448c66b9c664006ea6829360b9ac,63d8235747e25f4b65895e91ff64d778,4,NaN,Ótimo produto,2018-04-21 00:00:00,2018-04-22 02:17:31
63540,b93c7702979138924d704aea8350c8de,b2415aa888da881becd698f59da124b8,5,NaN,otimo,2018-04-12 00:00:00,2018-04-16 18:12:58
89277,bdd56d3c32a5088cdd2663d0dd355a17,835dc7ae3323802222f5f717e636e30e,1,NaN,"Entrega antes do prazo, o problema é que o scanner está com algum problema, pois não consigo conectar meu celular que é um moto G4 play, nem pelo wi-fi ou bluetooth, o sinal do scanner não aparece.",2018-04-26 00:00:00,2018-04-28 20:26:54
96241,33c73ce8240f1872da59f3afbaf70c07,543933b39ebd50e13884fca2829ccdf8,5,NaN,NaN,2018-03-14 00:00:00,2018-03-14 12:30:45
29791,4103387057b4966829ef7233ae5cb4ad,77f1ce3b8d86fff49b9c811f00f4dc13,1,NaN,NaN,2018-03-23 00:00:00,2018-03-27 23:28:50

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
13248,7c90d1f92845f3f2b566c81b55daf369,informatica_acessorios,59.0,111.0,1.0,300.0,50.0,5.0,20.0
8115,41ca153cf03e7b597a7b872ac78cad69,telefonia,58.0,734.0,3.0,250.0,17.0,4.0,12.0
19919,15d0beee06988a8a3a98717582e478e6,esporte_lazer,44.0,3674.0,1.0,1400.0,31.0,36.0,31.0
14010,6c037f9ff2d13c4236a23910ca598f42,utilidades_domesticas,58.0,700.0,2.0,1350.0,40.0,25.0,22.0
1397,c61cd4826ecfb4760797ad42c92ff8b1,eletroportateis,33.0,395.0,1.0,3700.0,28.0,39.0,39.0
9944,7e97894cc00196a56d6ec315c68b2353,esporte_lazer,20.0,420.0,4.0,3300.0,78.0,20.0,38.0
22133,3f64ba374e24f2a408729e5153b67283,ferramentas_jardim,59.0,448.0,3.0,250.0,36.0,3.0,12.0
7334,4d882bfbe6d83c0671d5b2776d46c248,moveis_sala,63.0,745.0,1.0,28100.0,97.0,9.0,75.0
14024,b4ba27d5fad6d6cde99f855d72b5afcf,eletrodomesticos,60.0,222.0,1.0,5700.0,55.0,19.0,46.0
24063,20ce586ed16cb9fb534673dfd97c2bd3,eletroportateis,48.0,977.0,2.0,500.0,20.0,20.0,20.0

,seller_id,seller_zip_code_prefix,seller_city,seller_state
713,4e326052e5dbba8adcd512f3450a307e,8020,sao paulo,SP
1345,1e47d8b6546eb3a77b1acddcc9406242,13015,campinas,SP
2487,26562f211dd1364af2a8596dc945e8ae,9785,sao bernardo do campo,SP
1656,f00e21b1e91a79653163b7fd8f293ff1,37795,andradas,SP
1397,e48cc16ab70bfa09e1401740dce0b3d7,16022,aracatuba,SP
638,7994081388d55b9cf976c050653dd359,1244,sao paulo,SP
914,570d4583587a5fe2d47c7be89b91ad27,2220,sao paulo,SP
566,e9874ae10b2d60d43917b6bbfa13a599,86604,rolandia,PR
2206,91f848e9f4be368f4318775aac733370,3029,sao paulo,SP
1126,e882b2a25a10b9c057cc49695f222c19,25963,teresopolis,RJ

                 product_category_name product_category_name_english
36  construcao_ferramentas_ferramentas       costruction_tools_tools
28             fashion_roupa_masculina         fashion_male_clothing
42                         moveis_sala         furniture_living_room
39                     livros_tecnicos               books_technical
20                               audio                         audio
40                     casa_construcao             home_construction
50      fashion_underwear_e_moda_praia       fashion_underwear_beach
18                     eletroportateis              small_appliances
68                     fraldas_higiene           diapers_and_hygiene
54                    artigos_de_natal            christmas_supplies