# Importing the required libraries

In [30]:
import os
import glob
import pandas as pd
pd.set_option('display.max_colwidth', None)

In [2]:
# 1. Grab all CSV paths from your target folder
folder_path = r"X:\Powerbi\Projects\Brazillian_ecommerce_analysis\Data"
all_files = glob.glob(os.path.join(folder_path, "*.csv"))

In [37]:
# 2. Extract structural data health profiles
file_profiles =[]
dfs =[]
column_def=[]
describe_prf=[]

for file in all_files:
    try:
        # Load sample or full file depending on size
        df_temp = pd.read_csv(file, nrows=1000) # Quick check on first 1000 rows
        
        profile = {
            "File_Name": os.path.basename(file),
            "Row_Count_Sample": len(df_temp),
            "Column_Count": len(df_temp.columns),
            #"Columns": list(df_temp.columns),
            "Missing_Values_Total": df_temp.isnull().sum().sum()
        }
        column_prf={
            "File_Name": os.path.basename(file),
            "Column names": list(df_temp.columns)
        }
        
        file_profiles.append(profile)
        column_def.append(column_prf)
        describe_prf.append(df_temp.describe(include="all"))
        
        # Keep track for final master merge
        #dfs.append(pd.read_csv(file))
    except Exception as e:
        print(f"⚠️ Structural error found in file {os.path.basename(file)}: {e}")

In [11]:
# Validate if all files match column layouts
profile_df = pd.DataFrame(file_profiles)
profile_df

# 3. If clean, consolidate into a master staging dataframe
#if len(dfs) > 0:
#    master_df = pd.concat(dfs, ignore_index=True)
#    # Save a staging dataset
#    master_df.to_csv(os.path.join(folder_path, "master_staging.csv"), index=False)

,File_Name,Row_Count_Sample,Column_Count,Missing_Values_Total
0,olist_customers_dataset.csv,1000,5,0
1,olist_geolocation_dataset.csv,1000,5,0
2,olist_orders_dataset.csv,1000,8,36
3,olist_order_items_dataset.csv,1000,7,0
4,olist_order_payments_dataset.csv,1000,5,0
5,olist_order_reviews_dataset.csv,1000,7,1449
6,olist_products_dataset.csv,1000,9,116
7,olist_sellers_dataset.csv,1000,4,0
8,product_category_name_translation.csv,71,2,0

In [ ]:
column_df=pd.DataFrame(column_def)
column_df

,File_Name,Column names
0,olist_customers_dataset.csv,"[customer_id, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state]"
1,olist_geolocation_dataset.csv,"[geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state]"
2,olist_orders_dataset.csv,"[order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]"
3,olist_order_items_dataset.csv,"[order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]"
4,olist_order_payments_dataset.csv,"[order_id, payment_sequential, payment_type, payment_installments, payment_value]"
5,olist_order_reviews_dataset.csv,"[review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]"
6,olist_products_dataset.csv,"[product_id, product_category_name, product_name_lenght, product_description_lenght, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm]"
7,olist_sellers_dataset.csv,"[seller_id, seller_zip_code_prefix, seller_city, seller_state]"
8,product_category_name_translation.csv,"[product_category_name, product_category_name_english]"

In [38]:
for item in describe_prf:
  display(item)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,1000,1000,1000.000000,1000,1000
unique,1000,999,NaN,379,26
top,06b8999e2fba1a1fbc88172c00ba8bc7,b6c083700ca8c135ba9f0f132930d4e8,NaN,sao paulo,SP
freq,1,2,NaN,157,422
mean,NaN,NaN,34373.614000,NaN,NaN
std,NaN,NaN,29541.443475,NaN,NaN
min,NaN,NaN,1008.000000,NaN,NaN
25%,NaN,NaN,11060.000000,NaN,NaN
50%,NaN,NaN,24235.000000,NaN,NaN
75%,NaN,NaN,55775.000000,NaN,NaN
max,NaN,NaN,99980.000000,NaN,NaN

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
count,1000.000000,1000.000000,1000.000000,1000,1000
unique,NaN,NaN,NaN,2,1
top,NaN,NaN,NaN,sao paulo,SP
freq,NaN,NaN,NaN,869,1000
mean,1029.308000,-23.545428,-46.637087,NaN,NaN
std,15.130501,0.004009,0.004609,NaN,NaN
min,1001.000000,-23.552555,-46.645820,NaN,NaN
25%,1017.000000,-23.548756,-46.641223,NaN,NaN
50%,1032.000000,-23.545949,-46.636325,NaN,NaN
75%,1045.000000,-23.542521,-46.633501,NaN,NaN
max,1050.000000,-23.534879,-46.627132,NaN,NaN

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,1000,1000,1000,1000,1000,989,975,1000
unique,1000,1000,6,1000,1000,985,975,349
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2018-06-11 14:54:00,2017-10-10 21:25:13,2018-02-21 00:00:00
freq,1,1,975,1,1,2,1,9

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
count,1000,1000.00000,1000,1000,1000,1000.000000,1000.000000
unique,877,NaN,832,456,877,NaN,NaN
top,0148d3df00cebda592d4e5f966e300cc,NaN,b532349fe46b38fbc7bb3914c1bdae07,4a3ca9315b744ce9f8e9374361493884,2017-08-24 19:24:32,NaN,NaN
freq,5,NaN,6,23,5,NaN,NaN
mean,NaN,1.16200,NaN,NaN,NaN,113.843090,19.704700
std,NaN,0.48579,NaN,NaN,NaN,146.043266,13.387775
min,NaN,1.00000,NaN,NaN,NaN,3.490000,0.000000
25%,NaN,1.00000,NaN,NaN,NaN,39.762500,12.900000
50%,NaN,1.00000,NaN,NaN,NaN,75.000000,16.200000
75%,NaN,1.00000,NaN,NaN,NaN,136.172500,21.335000
max,NaN,5.00000,NaN,NaN,NaN,1820.000000,102.630000

,order_id,payment_sequential,payment_type,payment_installments,payment_value
count,1000,1000.000000,1000,1000.000000,1000.000000
unique,1000,NaN,4,NaN,NaN
top,b81ef226f3fe1789b1e8b2acac839d17,NaN,credit_card,NaN,NaN
freq,1,NaN,735,NaN,NaN
mean,NaN,1.075000,NaN,2.815000,145.589830
std,NaN,0.444491,NaN,2.614883,193.158761
min,NaN,1.000000,NaN,1.000000,0.010000
25%,NaN,1.000000,NaN,1.000000,53.895000
50%,NaN,1.000000,NaN,1.000000,93.745000
75%,NaN,1.000000,NaN,4.000000,166.102500
max,NaN,8.000000,NaN,13.000000,2288.310000

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
count,1000,1000,1000.000000,115,436,1000,1000
unique,1000,1000,NaN,95,433,404,1000
top,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,NaN,recomendo,Gostei,2018-05-10 00:00:00,2018-01-18 21:46:59
freq,1,1,NaN,6,2,13,1
mean,NaN,NaN,4.055000,NaN,NaN,NaN,NaN
std,NaN,NaN,1.380536,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,5.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,5.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,5.000000,NaN,NaN,NaN,NaN

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,1000,971,971.000000,971.000000,971.000000,1000.000000,1000.000000,1000.000000,1000.000000
unique,1000,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,1e9e8ef04dbcff4541ed26657ea517e5,cama_mesa_banho,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,49.013388,754.185376,2.158599,2180.119000,30.182000,16.142000,22.758000
std,NaN,NaN,10.060888,600.292139,1.735492,4057.721467,16.971355,13.181031,12.132874
min,NaN,NaN,10.000000,42.000000,1.000000,50.000000,8.000000,2.000000,6.000000
25%,NaN,NaN,43.000000,337.500000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,NaN,NaN,52.000000,603.000000,1.000000,700.000000,24.000000,12.000000,19.500000
75%,NaN,NaN,57.000000,990.000000,3.000000,1762.500000,36.000000,20.000000,30.000000
max,NaN,NaN,64.000000,3939.000000,17.000000,30000.000000,105.000000,103.000000,105.000000

,seller_id,seller_zip_code_prefix,seller_city,seller_state
count,1000,1000.000000,1000,1000
unique,1000,NaN,318,19
top,3442f8959a84dea7ee197c632cb2df15,NaN,sao paulo,SP
freq,1,NaN,220,602
mean,NaN,31608.797000,NaN,NaN
std,NaN,32230.182461,NaN,NaN
min,NaN,1001.000000,NaN,NaN
25%,NaN,7089.250000,NaN,NaN
50%,NaN,15049.000000,NaN,NaN
75%,NaN,55084.250000,NaN,NaN
max,NaN,99730.000000,NaN,NaN

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1